import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { cpus,platform,release } from 'node:os';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
const work=process.env.GOAL_WORK || resolve('work2/remote-work');
const {chromium,firefox,webkit}=await import(process.env.GOAL_PLAYWRIGHT || resolve('work2/browser-validation/node_modules/playwright/index.mjs'));
const name=process.env.GOAL_ENGINE || 'chromium'; const engine={chromium,firefox,webkit}[name];
const phases=['baseline','candidate'];const html={};const hashes={};
for(const phase of phases){html[phase]=await readFile(resolve(work,phase+'.html'),'utf8');hashes[phase]=createHash('sha256').update(html[phase]).digest('hex');}
const hook=`globalThis.__goal={csvEsc,CONFIG,GeocodeParser,AppState,parseFileToRecords,lineIterator,readReverseResponseText,retryDelay,fetchReverseWithRetry,openReverseCacheDb,readPersistentReverseCache,writePersistentReverseCacheBatch,putReverseMemoryCache,REVERSE_PARSED_CACHE,get externalWrites(){return REVERSE_CACHE_EXTERNAL_WRITES;},get rowHint(){return REVERSE_CACHE_ROWS_UPPER_BOUND;},get syncChannel(){return REVERSE_CACHE_SYNC_CHANNEL;},REVERSE_CACHE_KEY_PREFIX,handleExport,runProcessingLoop,commitResult,renderCurrentPage,buildMapLink,revokeActiveDownloadUrl,downloadBlob,setDownloadSink(sink){downloadBlob=sink;},get downloadUrl(){return ACTIVE_DOWNLOAD_URL;},get exportTask(){return EXPORT_TASK;}};`;
const manualHook=`globalThis.__manual={parseU64,generateRandomDataFromNum,formatOutput};`;
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const phase=path.includes('candidate')?'candidate':'baseline';let body=html[phase];if(path.endsWith('probe.html'))body=body.replace('const MANUAL_GENERATION_HARD_LIMIT =',manualHook+'\nconst MANUAL_GENERATION_HARD_LIMIT =').replace(/\n  <\/script>\n<\/body>/,`\n${hook}\n  </script>\n</body>`);if(path.endsWith('icon.svg')){res.setHeader('content-type','image/svg+xml');body=await readFile(resolve(process.env.GOAL_REPO || process.cwd(),'icon.svg'));}else if(path.endsWith('site.webmanifest')){res.setHeader('content-type','application/manifest+json');body=await readFile(resolve(process.env.GOAL_REPO || process.cwd(),'site.webmanifest'));}else res.setHeader('content-type','text/html; charset=utf-8');res.end(body);}catch(e){res.writeHead(500).end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const launch={headless:true};if(process.env.GOAL_EXECUTABLE)launch.executablePath=process.env.GOAL_EXECUTABLE;
const browser=await engine.launch(launch);const results=[];const perf={};const errors=[];
const jsSources=text=>[...text.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const scriptIdentity=JSON.stringify(jsSources(html.baseline))===JSON.stringify(jsSources(html.candidate));
const meta={scriptIdentity,engine:name,version:browser.version(),node:process.version,os:platform()+' '+release(),cpu:cpus()[0].model,hashes,corpusSeed:'2026091412345678',plan:{performance:'separate frozen cache-path plan; unchanged CSV code uses retained evidence'}};
const corpus=JSON.parse(await readFile(resolve(work,'manual.json'),'utf8'));
const native=await readFile(resolve(work,'manual-rust.txt'),'utf8');
const expected=native.split(/^@@/m).slice(1).map(s=>{const at=s.indexOf('\n');const [id,used]=s.slice(0,at).split(',').map(Number);return {id,used,text:s.slice(at+1).trimEnd()};});
async function test(label,fn){const began=performance.now();try{const detail=await fn();results.push({label,status:'pass',ms:performance.now()-began,detail});}catch(e){results.push({label,status:'fail',ms:performance.now()-began,error:String(e),stack:e.stack});}console.log('GOAL_CASE '+JSON.stringify(results.at(-1)));}
async function pageFor(phase,probe=false,options={}){const context=await browser.newContext({acceptDownloads:true,...options});const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push({phase,error:e.message}));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:'',contentType:'text/css'}));await page.goto(`${origin}/${phase}${probe?'.probe':''}.html`);return {page,context};}
async function upload(page,text){await page.locator('#file').setInputFiles({name:'random_data.txt',mimeType:'text/plain',buffer:Buffer.isBuffer(text)?text:Buffer.from(text)});await page.locator('#parse').click();}
const sample='대한민국 위경도: 37.5, 127\n세계 위경도: -33.9, 151.2\n대한민국 위경도: 37.5, 127\n';
const geocode=lat=>({features:[{properties:{geocoding:{country_code:lat<0?'au':'kr',country:lat<0?'Australia':'대한민국',state:lat<0?'New South Wales':'서울특별시',city:lat<0?'Sydney':'서울특별시',district:lat<0?'':'강남구',name:'=위험 <img src=x>',type:'city',label:lat<0?'Sydney, Australia':'서울특별시, "강남구"\n역삼동'}}}]});
for(const phase of phases){
 await test(phase+'/UI: parse, request spacing, dedup cache, maps, filters, CSV, theme, names',async()=>{
  const {page,context}=await pageFor(phase);try{const requests=[];await page.route('https://nominatim.openstreetmap.org/**',async r=>{requests.push(performance.now());await r.fulfill({json:geocode(Number(new URL(r.request().url()).searchParams.get('lat')))});});await upload(page,sample);await page.waitForFunction(()=>document.querySelector('#cnt-total').textContent==='3');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#cnt-success').textContent==='3');assert.equal(requests.length,2);assert.ok(requests[1]-requests[0]>=950);assert.equal(await page.locator('#tbl tbody tr').count(),3);assert.equal(await page.locator('#tbl tbody img').count(),0);
  await page.locator('.map-btn').first().click();await page.waitForFunction(()=>document.querySelector('#map-popover').matches(':popover-open'));const links=await page.locator('#map-popover-links a').evaluateAll(as=>as.map(a=>({href:a.href,rel:a.rel})));assert.equal(links.length,4);assert.ok(links.every(a=>a.href.startsWith('https://')));await page.keyboard.press('Escape');await page.locator('#filter-q').fill('Sydney');await page.waitForFunction(()=>document.querySelectorAll('#tbl tbody tr').length===1);await page.locator('#filter-clear').click();await page.waitForFunction(()=>document.querySelectorAll('#tbl tbody tr').length===3);
  const dl=page.waitForEvent('download');await page.locator('#export').click();const d=await dl;const csv=await readFile(await d.path());assert.ok(csv.subarray(0,3).equals(Buffer.from([239,187,191])));assert.ok(csv.toString('utf8').includes("'=위험"));assert.ok(csv.toString('utf8').includes('OpenStreetMap'));assert.ok(csv.toString('utf8').includes('""강남구""'));
  const theme=await page.locator('#theme-toggle').getAttribute('aria-pressed');await page.locator('#theme-toggle').click();assert.notEqual(await page.locator('#theme-toggle').getAttribute('aria-pressed'),theme);await page.reload();assert.notEqual(await page.locator('#theme-toggle').getAttribute('aria-pressed'),theme);
  const missing=await page.locator('button').evaluateAll(bs=>bs.filter(b=>!(b.getAttribute('aria-label')||b.textContent.trim()||b.title)).map(b=>b.id));assert.deepEqual(missing,[]);assert.equal(await page.locator('#status-live').getAttribute('role'),'status');return {requests:2,spacingMs:requests[1]-requests[0],csvBytes:csv.length};}finally{await context.close();}
 });
 await test(phase+'/UI: pause, resume, abort, no late result',async()=>{const {page,context}=await pageFor(phase);let releaseFirst,releaseSecond;const first=Promise.withResolvers(),second=Promise.withResolvers();try{let count=0;await page.route('https://nominatim.openstreetmap.org/**',async r=>{count++;if(count===1)await new Promise(resolve=>{releaseFirst=resolve;first.resolve();});if(count===2)await new Promise(resolve=>{releaseSecond=resolve;second.resolve();});try{await r.fulfill({json:geocode(37)});}catch{}});await upload(page,'대한민국 위경도: 35.1, 127\n대한민국 위경도: 35.2, 127\n대한민국 위경도: 35.3, 127');await page.waitForFunction(()=>!document.querySelector('#start').disabled);await page.locator('#start').click();await first.promise;await page.locator('#pause').click();releaseFirst();await page.waitForFunction(()=>!document.querySelector('#resume').disabled);assert.equal(count,1);await page.locator('#resume').click();await second.promise;await page.locator('#stop').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('중지'));releaseSecond();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await page.locator('#cnt-success').innerText(),'1');await page.waitForTimeout(1100);assert.equal(await page.locator('#cnt-success').innerText(),'1');return {requests:count,completed:1,lateCompletions:0};}finally{releaseFirst?.();releaseSecond?.();await context.close();}});
 await test(phase+'/UI: manual save, dialog validation/cancel, clear, mobile and focus',async()=>{const {page,context}=await pageFor(phase,false,{viewport:{width:390,height:844},reducedMotion:'reduce'});try{await page.locator('.manual-rng summary').click();await page.locator('#num64').fill(corpus[4][0]);await page.locator('#suppValues').fill(corpus[4].slice(1).join(' '));await page.locator('#runBtn').click();await page.waitForFunction(()=>!document.querySelector('#saveOutput').disabled);assert.equal((await page.locator('#output').innerText()).trim(),expected[4].text);const dl=page.waitForEvent('download');await page.locator('#saveOutput').click();const d=await dl;const data=await readFile(await d.path());assert.equal(data.toString('utf8'),'\ufeff'+expected[4].text+'\n');await page.locator('#clearBtn').click();assert.equal(await page.locator('#output .coords-content').innerText(),'');await page.locator('#num64').fill('0');await page.locator('#suppValues').fill('');await page.locator('#runBtn').click();await page.locator('#supp-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#supp-dialog').getAttribute('aria-labelledby'),'supp-dialog-title');await page.locator('#supp-dialog-values').fill('-1');await page.locator('#supp-dialog button[type=submit]').click();assert.equal(await page.locator('#supp-dialog-values').getAttribute('aria-invalid'),'true');await page.keyboard.press('Escape');await page.locator('#supp-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#runBtn').isDisabled(),false);const layout=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert.ok(layout.scroll<=layout.width+1);return {saveBytes:data.length,layout};}finally{await context.close();}});
 await test(phase+'/HTTP retry bounds and request timeout',async()=>{const {page:net,context:netContext}=await pageFor(phase,true);try{await net.waitForFunction(()=>!!globalThis.__goal);const counts={};await net.route('https://nominatim.openstreetmap.org/**',async r=>{const kind=new URL(r.request().url()).searchParams.get('case');counts[kind]=(counts[kind]||0)+1;if(kind==='400')await r.fulfill({status:400,body:'bad'});else if(kind==='500')await r.fulfill({status:500,body:'bad'});else if(kind==='json')await r.fulfill({status:200,body:'{'});else if(kind==='429')await r.fulfill(counts[kind]===1?{status:429,headers:{'retry-after':'1'},body:'wait'}:{json:{ok:true}});else if(kind==='timeout'){await new Promise(resolve=>setTimeout(resolve,11000));try{await r.fulfill({json:{late:true}});}catch{}}else await r.abort();});for(const kind of ['400','500','json','429','network','timeout']){const out=await net.evaluate(async kind=>{try{return {ok:true,value:await __goal.fetchReverseWithRetry('https://nominatim.openstreetmap.org/reverse?case='+kind,new AbortController().signal)};}catch(e){return {ok:false,error:e.name};}},kind);assert.equal(out.ok,kind==='429');}assert.deepEqual(counts,{'400':1,'500':3,json:1,'429':2,network:3,timeout:3});return counts;}finally{await netContext.close();}});
 await test(phase+'/clipboard snapshot, rejection and stale completion',async()=>{const {page:clip,context:clipContext}=await pageFor(phase);try{await clip.locator('.manual-rng summary').click();await clip.locator('#num64').fill(corpus[4][0]);await clip.locator('#suppValues').fill(corpus[4].slice(1).join(' '));await clip.locator('#runBtn').click();await clip.waitForFunction(()=>!document.querySelector('#copyOutput').disabled);await clip.evaluate(()=>{globalThis.__clipboardWrites=[];Object.defineProperty(navigator.clipboard,'write',{configurable:true,value(items){__clipboardWrites.push(items);return new Promise((resolve,reject)=>{globalThis.__resolveClipboard=resolve;globalThis.__rejectClipboard=reject;});}});});await clip.locator('#copyOutput').click();await clip.waitForFunction(()=>__clipboardWrites.length===1);const text=await clip.evaluate(async()=>await (await __clipboardWrites[0][0].getType('text/plain')).text());assert.equal(text,expected[4].text+'\n');await clip.locator('#clearBtn').click();await clip.evaluate(()=>__resolveClipboard());await clip.waitForTimeout(50);assert.equal(await clip.locator('#meta').innerText(),'');assert.equal(await clip.locator('#error').innerText(),'');await clip.locator('#runBtn').click();await clip.waitForFunction(()=>!document.querySelector('#copyOutput').disabled);await clip.locator('#copyOutput').click();await clip.waitForFunction(()=>__clipboardWrites.length===2);await clip.evaluate(()=>__rejectClipboard(new DOMException('Denied test clipboard','NotAllowedError')));await clip.waitForFunction(()=>document.querySelector('#error').textContent.includes('Denied'));assert.equal(await clip.locator('#copyOutput').isDisabled(),false);return {secureContext:await clip.evaluate(()=>isSecureContext),snapshotBytes:Buffer.byteLength(text),staleUiWrites:0,rejectionReported:true,mode:'native ClipboardItem + controlled pending/rejected clipboard boundary'};}finally{await clipContext.close();}});
 const {page,context}=await pageFor(phase,true);try{
 await page.locator('.manual-rng summary').click();await page.waitForFunction(()=>!!globalThis.__manual&&!!globalThis.__goal);
 await test(phase+'/common Rust num64/supp exact conversion',async()=>{const got=await page.evaluate(rows=>rows.map(row=>{let used=0;const d=__manual.generateRandomDataFromNum(BigInt(row[0]),()=>({value:BigInt(row[++used]),bitsRemaining:64}));return {text:__manual.formatOutput(d),used};}),corpus);for(let i=0;i<got.length;i++){assert.equal(got[i].text,expected[i].text,'output '+i);assert.equal(got[i].used,expected[i].used,'supp consumption '+i);}return {compared:got.length,lines:got.length*17};});
 await test(phase+'/input rejection, stream boundaries and cancellation',async()=>{const r=await page.evaluate(async()=>{const g=__goal,s=new AbortController().signal;let count=0;for(const raw of ['','-1','0b1','0o7','18446744073709551616','1'.repeat(65),'NaN']){try{__manual.parseU64(raw);throw Error('accepted '+raw);}catch(e){if(e.message.startsWith('accepted'))throw e;count++;}}for(const raw of ['0','+1','0xFFFFFFFFFFFFFFFF','18446744073709551615'])__manual.parseU64(raw);const good='\ufeff대한민국 위경도： +37.5，127\r\n세계 위경도: -90,-180\r대한민국 위경도: 90,180\n세계 위경도: 91,0';const parsed=await g.parseFileToRecords(new File([good],'x.txt'),s);if(parsed.length!==3)throw Error('coordinate range');for(const bytes of [new Uint8Array([255]),'x'.repeat(g.CONFIG.INPUT_LINE_HARD_LIMIT+1),'세계 위경도: 0,0\n'.repeat(5001)]){try{await g.parseFileToRecords(new File([bytes],'x.txt'),s);throw Error('accepted invalid file');}catch(e){if(e.message==='accepted invalid file')throw e;count++;}}const bytes=new TextEncoder().encode('가\r\n나\r다\n라');for(const width of [1,2,3,7]){let i=0;const stream=new ReadableStream({pull(c){if(i===bytes.length)c.close();else{const end=Math.min(i+width,bytes.length);c.enqueue(bytes.slice(i,end));i=end;}}});const lines=[];for await(const l of g.lineIterator(stream,s))lines.push(l);if(JSON.stringify(lines)!==JSON.stringify(['가','나','다','라']))throw Error('chunk '+width);}const ac=new AbortController();ac.abort();try{await g.parseFileToRecords(new File(['세계 위경도: 0,0'],'x.txt'),ac.signal);throw Error('accepted aborted');}catch(e){if(e.name!=='AbortError')throw e;}return {rejects:count,coordinateRows:3,chunkWidths:4,aborted:true};});return r;});
 await test(phase+'/response limits, UTF8, parser bounds, stream release and retry caps',async()=>await page.evaluate(async()=>{const g=__goal,s=new AbortController().signal;let rejects=0;for(const response of [new Response('a',{headers:{'content-length':String(g.CONFIG.REVERSE_RESPONSE_MAX_BYTES+1)}}),new Response(new Uint8Array([255])),new Response('x'.repeat(g.CONFIG.REVERSE_RESPONSE_MAX_BYTES+1))]){try{await g.readReverseResponseText(response,s);throw Error('accepted bad response');}catch(e){if(e.message==='accepted bad response')throw e;rejects++;}if(response.body.locked)throw Error('stream locked');}try{g.GeocodeParser.parse({features:[{properties:{geocoding:{label:'a'.repeat(4097)}}}]});throw Error('accepted text');}catch(e){if(e.message==='accepted text')throw e;rejects++;}if(g.retryDelay(new Response('',{status:429,headers:{'retry-after':'999999'}}),1)!==60000)throw Error('retry cap');return {rejects};}));
 await test(phase+'/cache bound, persistence, expiry rejection and version cleanup',async()=>await page.evaluate(async()=>{const g=__goal,parsed={addr:{sido:'s',sigungu:'g',eupmyeon:'e',tag:'t',fullAddr:'a'},kind:'KR'};for(let i=0;i<5010;i++)g.putReverseMemoryCache('key'+i,parsed);if(g.REVERSE_PARSED_CACHE.size!==5000||g.REVERSE_PARSED_CACHE.has('key0'))throw Error('memory bound');const ac=new AbortController();await g.writePersistentReverseCacheBatch([{cacheKey:'37,127',parsed}],ac.signal);const m=new Map([['37,127',null]]);await g.readPersistentReverseCache(m,ac.signal);if(m.get('37,127')?.addr.fullAddr!=='a')throw Error('persistence');g.REVERSE_PARSED_CACHE.clear();const db=await g.openReverseCacheDb();await new Promise((resolve,reject)=>{const tx=db.transaction(g.CONFIG.REVERSE_CACHE_STORE,'readwrite');tx.objectStore(g.CONFIG.REVERSE_CACHE_STORE).put({key:g.REVERSE_CACHE_KEY_PREFIX+'expired',savedAt:Date.now()-g.CONFIG.REVERSE_CACHE_TTL_MS-1,parsed});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});const old=new Map([['expired',null]]);await g.readPersistentReverseCache(old,ac.signal);if(old.get('expired')!==null)throw Error('expired accepted');await new Promise((resolve,reject)=>{const request=indexedDB.open(g.CONFIG.REVERSE_CACHE_DB_NAME,5);request.onsuccess=()=>{request.result.close();resolve();};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('versionchange did not close connection'));});return {memoryMax:5000,persisted:1,expiredRejected:true,versionchange:true};}));
 await test(phase+'/paging, export lifetime and stale generation',async()=>{const detail=await page.evaluate(()=>{const g=__goal;const records=Array.from({length:201},(_,i)=>({set:'KR',latStr:String(i/10),lonStr:'127',cacheKey:i+',127',result:null}));g.AppState.droppedFile=new File([''],'random_data.txt');g.AppState.setRecords(records);const parsed={addr:{sido:'s',sigungu:'g',eupmyeon:'e',tag:'t',fullAddr:'a'},kind:'KR'};for(let i=0;i<records.length;i++)g.commitResult(i,parsed,false);g.renderCurrentPage();return records.length;});assert.equal(await page.locator('#tbl tbody tr').count(),100);await page.locator('#page-next').click();await page.locator('#page-next').click();await page.waitForFunction(()=>document.querySelectorAll('#tbl tbody tr').length===1);const dl=page.waitForEvent('download');await page.locator('#export').click();await dl;assert.equal(await page.evaluate(()=>!!__goal.downloadUrl),true);await page.evaluate(()=>__goal.revokeActiveDownloadUrl());assert.equal(await page.evaluate(()=>__goal.downloadUrl),null);const downloads=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await page.evaluate(async()=>{const task=__goal.handleExport();__goal.AppState.reset();await task;});await page.waitForTimeout(100);assert.equal(downloads.length,0);return {rows:detail,pageLimit:100,staleDownloads:0};});
 }finally{await context.close();}
}
for (const phase of phases) {
 await test(phase+'/cross-tab bounded ownership and cache recovery',async()=>{
  const {page,context}=await pageFor(phase,true); const peer=await context.newPage();
  try {
   await peer.goto(origin+'/'+phase+'.probe.html');
   await page.evaluate(()=>{globalThis.__ack='';__goal.syncChannel.addEventListener('message',({data})=>{if(data?.[0]===2)globalThis.__ack=data[1];});});
   let sequence=0;
   async function send(messages){const ack=String(++sequence);await peer.evaluate(({messages,ack})=>{for(const data of messages)__goal.syncChannel.postMessage(data);__goal.syncChannel.postMessage([2,ack]);},{messages,ack});await page.waitForFunction(ack=>__ack===ack,ack);}
   const state=()=>page.evaluate(()=>({size:__goal.externalWrites?.size??null,units:__goal.externalWrites?[...__goal.externalWrites].reduce((n,s)=>n+s.length,0):0,hint:__goal.rowHint}));
   await send([null,[],[0,3],[3,'ignored'],[0,'bad','shape']]);assert.equal((await state()).size,0);
   const tokens=Array.from({length:64},(_,i)=>String(i).padEnd(128,'x'));
   await send(tokens.map(s=>[0,s]));assert.deepEqual(await state(),{size:64,units:8192,hint:null});
   await send([[0,tokens[0]]]);assert.equal((await state()).size,64);
   await send(tokens.map(s=>[1,s]));assert.equal((await state()).size,0);
   await send(Array.from({length:10000},(_,i)=>[0,'orphan-'+i]));
   const overflow=await state();assert.equal(overflow.size,phase==='candidate'?null:10000);
   await peer.close();
   const cache=await page.evaluate(async()=>{const g=__goal,parsed={addr:{sido:'s',sigungu:'g',eupmyeon:'e',tag:'t',fullAddr:'after overflow'},kind:'KR'},signal=new AbortController().signal;
    await g.writePersistentReverseCacheBatch(Array.from({length:32},(_,i)=>({cacheKey:'orphan-cache-'+i,parsed})),signal);g.REVERSE_PARSED_CACHE.clear();const map=new Map(Array.from({length:32},(_,i)=>['orphan-cache-'+i,null]));await g.readPersistentReverseCache(map,signal);return {found:[...map.values()].filter(v=>v?.addr.fullAddr==='after overflow').length,hint:g.rowHint};});
   assert.equal(cache.found,32);assert.equal(cache.hint,null);
   await page.reload();await page.waitForFunction(()=>!!globalThis.__goal);assert.equal((await state()).size,0);
   const sender=await context.newPage();await sender.goto(origin+'/'+phase+'.probe.html');
   await page.evaluate(()=>{globalThis.__ack='';__goal.syncChannel.addEventListener('message',({data})=>{if(data?.[0]===2)globalThis.__ack=data[1];});});
   await sender.evaluate(()=>{__goal.syncChannel.postMessage([0,'x'.repeat(1048576)]);__goal.syncChannel.postMessage([2,'long']);});await page.waitForFunction(()=>__ack==='long');
   const long=await state();assert.equal(long.units,phase==='candidate'?0:1048576);
   return {invalidIgnored:true,capacity:64,maxTokenUnits:128,duplicateAtCapacity:true,pairedCompletion:true,overflow,long,cache,reloadRestored:true,transport:'real same-origin BroadcastChannel between pages'};
  } finally {await context.close();}
 });
}

// Fixed corpus independent CSV encoder: RFC 4180 quoting plus existing formula prefix contract.
const chars=['','abc','가나다','Sydney','a,b','"','a"b','\r','\n','\t','=SUM(A1)','+1','-1','@x','\u0000','😀','\ud800'];
const csvInputs=[null,undefined,0,-1,true,...chars];for(const a of chars)for(const b of chars)csvInputs.push(a+b);
const oracle=v=>{let s=String(v??'');if(s&&['\t','\r','\n','=','+','-','@'].includes(s[0]))s="'"+s;return [...s].some(c=>['"',',','\r','\n'].includes(c))?'"'+s.split('"').join('""')+'"':s;};
const expectedCsv=csvInputs.map(oracle);
const pages={};for(const phase of phases){pages[phase]=await pageFor(phase,true);await pages[phase].page.waitForFunction(()=>!!globalThis.__goal);await test(phase+'/CSV independent oracle',async()=>{const out=await pages[phase].page.evaluate(a=>a.map(__goal.csvEsc),csvInputs);assert.deepEqual(out,expectedCsv);return {compared:out.length};});}
const exportBytes={};
for(const phase of phases)await pages[phase].context.close();
const memory={baseline:[],candidate:[]};
function browserRss(){const lines=execFileSync('ps',['-e','-o','pid=,ppid=,rss='],{encoding:'utf8'}).trim().split('\n').map(l=>l.trim().split(/\s+/).map(Number));const children=new Set([process.pid]);for(let i=0;i<6;i++)for(const [pid,ppid] of lines)if(children.has(ppid))children.add(pid);return lines.filter(([pid])=>pid!==process.pid&&children.has(pid)).reduce((sum,row)=>sum+row[2],0);}
for(let i=-1;i<7;i++){for(const phase of i%2===0?phases:[...phases].reverse()){const {page,context}=await pageFor(phase,true);await page.waitForFunction(()=>!!globalThis.__goal);await page.evaluate(()=>{let sum=0;for(let n=0;n<100000;n++)for(const s of ['서울특별시','강남구','a"b','a,b','x'.repeat(128)])sum+=__goal.csvEsc(s).length;globalThis.__checksum=sum;});await page.requestGC();if(i>=0)memory[phase].push(browserRss());await context.close();}}

await test('uncaught page errors',()=>{assert.deepEqual(errors,[]);return {count:0};});
const report={...meta,results,perf,exportBytes,memory,passed:results.filter(r=>r.status==='pass').length,total:results.length};await mkdir(resolve(work,'results'),{recursive:true});await writeFile(resolve(work,'results',name+'.json'),JSON.stringify(report,null,2));console.log('GOAL_RESULT_JSON='+JSON.stringify(report));await browser.close();server.close();if(report.passed!==report.total)process.exitCode=1;
