const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const deps=process.env.AUDIT_NODE_MODULES;
const {chromium,firefox,webkit}=require(path.join(deps,'playwright'));
const acorn=require(path.join(deps,'acorn')),walk=require(path.join(deps,'acorn-walk')),postcss=require(path.join(deps,'postcss')),selectorParser=require(path.join(deps,'postcss-selector-parser')),parse5=require(path.join(deps,'parse5')),{Linter}=require(path.join(deps,'eslint'));
const evidence='/tmp/revgeo-audit-evidence';fs.mkdirSync(evidence,{recursive:true});
const before=fs.readFileSync(process.env.AUDIT_BASELINE,'utf8'),after=fs.readFileSync(path.resolve(__dirname,'../revgeo.html'),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
assert.equal(sha(before),'7e33de138da0a21ea33b4ed06334cc2055f293a04f269c61e9748c670a8692e6');
assert.equal(sha(after),'98731784caad6d4906a350544a0c53625c49ddf559e59cfdbf4d1b9eb3e2a157');
const sources=[before,after],stats=[];
for(let v=0;v<2;v++){
 const text=sources[v],doc=parse5.parse(text,{sourceCodeLocationInfo:true}),ids=new Set(),classes=new Set(),tags=new Set(),refs=[],strings=new Set(),cssClasses=new Set(),cssProps=new Set(),customDefs=new Set(),customReads=new Set(),members=[],calls=[],properties=[],js=[],selectors=[];
 let elements=0,attrs=0,classTokens=0,cssRules=0,cssDecls=0,keyframes=0;
 function visit(n){if(n.tagName){elements++;tags.add(n.tagName);attrs+=(n.attrs||[]).length;for(const a of n.attrs||[]){if(a.name==='id')ids.add(a.value);if(a.name==='class'){a.value.split(/\s+/).forEach(x=>classes.add(x));classTokens+=a.value.split(/\s+/).length;}if(['for','aria-labelledby','aria-describedby','commandfor','popovertarget'].includes(a.name))refs.push(a.value);}}for(const c of n.childNodes||[])visit(c);if(n.content)visit(n.content);}visit(doc);
 const lint=[];
 for(const m of text.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){
  const sourceType=m[1].includes('module')?'module':'script',code=m[2],ast=acorn.parse(code,{ecmaVersion:'latest',sourceType,locations:true});
  lint.push(...new Linter().verify(code,{languageOptions:{ecmaVersion:'latest',sourceType},rules:{'no-unused-vars':['error',{vars:'all',args:'all',caughtErrors:'all'}],'no-unreachable':'error','no-unused-labels':'error','no-unused-private-class-members':'error','no-constant-binary-expression':'error','no-useless-assignment':'error'}}));
  walk.simple(ast,{Literal(n){if(typeof n.value==='string')strings.add(n.value);},VariableDeclarator(n){if(n.id.type==='Identifier'){js.push({type:'binding',name:n.id.name});if(n.init?.type==='ObjectExpression')for(const p of n.init.properties)if(p.type==='Property')properties.push({owner:n.id.name,name:p.key.name??p.key.value});}},FunctionDeclaration(n){js.push({type:'function',name:n.id.name});},ClassDeclaration(n){js.push({type:'class',name:n.id.name});},MemberExpression(n){members.push({owner:code.slice(n.object.start,n.object.end),property:n.computed?n.property.type==='Literal'?n.property.value:'<dynamic>':n.property.name});},CallExpression(n){if(n.callee.type==='Identifier')calls.push({name:n.callee.name,arity:n.arguments.length});}});
 }
 for(const m of text.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)){
  const css=postcss.parse(m[1]);css.walkRules(r=>{if(r.parent.type==='atrule'&&/keyframes$/.test(r.parent.name))return;cssRules++;selectors.push(r.selector);selectorParser(s=>s.walkClasses(c=>cssClasses.add(c.value))).processSync(r.selector);});
  css.walkAtRules(a=>{if(/keyframes$/.test(a.name))keyframes++;});
  css.walkDecls(d=>{cssDecls++;cssProps.add(d.prop);if(d.prop.startsWith('--'))customDefs.add(d.prop);for(const m of d.value.matchAll(/var\((--[\w-]+)/g))customReads.add(m[1]);});
 }
 assert.equal(lint.length,2);assert.ok(lint.every(x=>x.ruleId==='no-unused-vars'&&x.message==="'_' is defined but never used."));
 assert.deepEqual(refs.flatMap(s=>s.split(/\s+/).filter(id=>!ids.has(id))),[]);
 const unreferenced={};for(const owner of ['domElements','CONFIG','AppState','RENDER_CACHE','SR_STATUS_CACHE'])unreferenced[owner]=properties.filter(x=>x.owner===owner&&!members.some(m=>m.owner===owner&&(m.property===x.name||m.property==='<dynamic>'))).map(x=>x.name);
 const unusedClasses=[...classes].filter(c=>!cssClasses.has(c)&&!strings.has(c));
 if(v===0){assert.deepEqual(unreferenced.domElements,['progLabel']);assert.equal(unusedClasses.length,7);}else{for(const [owner,a] of Object.entries(unreferenced))assert.deepEqual(a,owner==='domElements'?['progLabel']:[]);assert.deepEqual(unusedClasses,stats[0].unusedClasses);}
 assert.deepEqual([...customDefs].filter(x=>!customReads.has(x)&&!text.includes('.setProperty("'+x+'"')),[]);
 const item={sha256:sha(text),rawBytes:Buffer.byteLength(text),physicalLines:text.split(/\r?\n/).length,codeLines:text.split(/\r?\n/).filter(s=>s.trim()&&!/^(\/\/|\/\*|\*|<!--)/.test(s.trim())).length,jsDeclarations:js.length,namedDeclarations:js.filter(x=>x.type!=='binding').length,cssRules,cssDecls,keyframes,customProperties:customDefs.size,ids:ids.size,classes:classes.size,tags:tags.size,elements,attrs,classTokens,htmlReferenceCount:refs.length,unusedClasses,unreferenced,privateCalls:calls.filter(c=>['pickAdminName','maintainReverseCacheRows','createDataSet','generateRandomDataFromNum'].includes(c.name)),intentionalLintFindings:lint.map(x=>({rule:x.ruleId,message:x.message})),selectors,cssProps:[...cssProps]};
 stats.push(item);
}
assert.equal(stats[0].elements,stats[1].elements);assert.equal(stats[0].attrs-stats[1].attrs,0);assert.equal(stats[0].classTokens-stats[1].classTokens,0);assert.equal(stats[0].codeLines-stats[1].codeLines,2);
fs.writeFileSync(path.join(evidence,'static-results.json'),JSON.stringify(stats,null,2));
const expose=function(){
 globalThis.__audit={
  CONFIG,parse:GeocodeParser.parse,maintain:maintainReverseCacheRows,
  seed(n=4,size=10,page=0,status='idle',pending=false){
   const addr={sido:'서울',sigungu:'중구',eupmyeon:'명동',tag:'시청',fullAddr:'서울 중구 명동 시청'};
   const records=Array.from({length:n},(_,i)=>({set:['KR','KP','WORLD'][i%3],latStr:'37.5665',lonStr:'126.9780',cacheKey:'fixture-'+i,result:pending?null:i%4===3?{kind:'에러',error:'fixture error'}:{kind:['KR','KP','WORLD'][i%3],addr}}));
   AppState.setRecords(records,status);AppState.processed=pending?0:n;AppState.cntFail=pending?0:Math.floor(n/4);AppState.visibleIndices=pending?[]:records.map((_,i)=>i);AppState.page=page;resultPageSize=size;renderCurrentPage(true);renderFrame();
  },
  state(status){AppState.task=status==='idle'?null:{status,controller:new AbortController(),resume:null};updateUIState();},
  page(){return AppState.page;},
  generate(raw){let n=123456789n;const next=()=>{n=BigInt.asUintN(64,n*6364136223846793005n+1442695040888963407n);return{value:n,bitsRemaining:64};};return __auditRng.format(__auditRng.gen(BigInt(raw),next));}
 };
};
function instrument(t,closed=false){assert.equal((t.match(/      initializeManualRng\(\);/g)||[]).length,1);t=t.replace('      initializeManualRng();','      globalThis.__auditRng={gen:generateRandomDataFromNum,format:formatOutput,parse:parseU64,tokens:iterU64Tokens};\n      initializeManualRng();');if(closed)t=t.replace(/(<details\b[^>]*class="manual-rng"[^>]*?)\sopen(?=[\s>])/,'$1');const i=t.lastIndexOf('</script>');return t.slice(0,i)+'('+expose.toString()+')();'+t.slice(i);}
const pagesText=sources.map(s=>instrument(s));
const server=http.createServer((req,res)=>{const v=req.url.includes('baseline')?0:1;if(!/^\/(?:baseline|candidate|closed-baseline|closed-candidate)$/.test(req.url))return res.writeHead(404).end();res.setHeader('content-type','text/html;charset=utf-8');res.end(req.url.includes('closed')?instrument(sources[v],true):pagesText[v]);});
const corpus=[null,{}, {features:[]}, ...[
 {country_code:'kr',city:'서울특별시',city_district:'중구',name:'명동',label:'명동, 중구, 서울',admin:{level4:'서울특별시',level6:'중구',level8:'명동'}},
 {country_code:'kr',state:'경기도',city:'수원시',city_district:'팔달구',name:'인계동',label:'인계동, 팔달구',admin:{level4:'경기도',level8:'팔달구',level10:'인계동'}},
 {country_code:'kr',state:'경기도',county:'가평군',village:'청평리',label:'청평리, 청평면',admin:{level8:'청평면'}},
 {country_code:'kr',name:'천안시',label:'천안시, 신부동',admin:{level4:'충청남도'}},
 {country_code:'kp',city:'평양시',city_district:'중구역',label:'평양시, 중앙동',admin:{level8:'중앙동'}},
 {country_code:'us',state:'California',city:'San Francisco',city_district:'Mission',name:'Park',label:'Park, Mission',type:'park',locality:'Local'},
 {country_code:'gb',state:'England',city:'London',city_district:'Westminster',name:'Westminster',type:'district'},
 {country_code:'fr',country:'France',name:'Paris',type:'city',label:'Paris, France',admin:{level4:'France'}},
 {country:'South Korea',state:'강원특별자치도',county:'홍천군',town:'홍천읍',label:'홍천읍, 홍천군'},
 {country_code:'aq',country:'Antarctica',name:'Antarctica',label:'Antarctica'},
 {country_code:'zz',label:', , Name, District',admin:{level4:123,level6:null},state:[],name:{}},
 {country_code:'zz',label:'x'.repeat(4096)}, {country_code:'zz',label:'x'.repeat(4097)},
 {country_code:'zz',name:'x'.repeat(4097)}, {country_code:'kr',city:'부산광역시',county:'기장군',city_district:'해운대구',suburb:'우동',label:'우동, 해운대구'},
 {country_code:'zz',state:'S',city:'A',city_district:'B',locality:'B',type:'city',label:'A B, B'}
].map(geocoding=>({features:[{properties:{geocoding}}]}))];
const numbers=['0','1','18446744073709551615','77162851027281784',...Array.from({length:128},(_,i)=>BigInt.asUintN(64,BigInt(i)*6364136223846793005n+1442695040888963407n).toString())];
const output={contract:{baseline:'081f3c8326104dd74060924f69cb29f2c4a48557',candidateBlob:'8b6100ca9e32bb8656c056d8a553326f514e7c7f',pairs:40,warmup:10,changedWorkloads:['parser','rng-single','rng-bulk','ui-state','page-10','page-100','nav-5000','current-page','filter-clear-scheduling'],repetitions:{parser:200,rngSingle:100,rngBulk:128,uiState:1000,page:20,filterClear:1000},bound:'candidate <= baseline*1.05+0.05 ms per operation; paired median delta bootstrap 99% upper',screenshots:'diagnostic only; exact computed author style/geometry/text hashes + ARIA are gates; unmodified original corner raster variability observed locally',staticExpected:{retainedPositionalUnusedArgs:2,unusedClasses:7,retainedStaticAndTemplateClasses:7,unreferencedDomProperties:1},sourceSHA256:sources.map(sha),runner:process.env.GITHUB_RUN_ID||null,node:process.version},browsers:{}};
async function configure(c){await c.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/css',body:''}));await c.route('https://nominatim.openstreetmap.org/reverse**',r=>{const kr=new URL(r.request().url()).searchParams.get('lat')==='37.5665';return r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({features:[{properties:{geocoding:kr?{country_code:'kr',label:'서울특별시 중구 시청',name:'시청',city:'서울특별시',city_district:'중구',admin:{level4:'서울특별시',level6:'중구'}}:{country_code:'aq',label:'Antarctica',name:'Antarctica',country:'Antarctica'}}}]})});});}
async function digestState(p){return p.evaluate(async props=>{const data=Array.from(document.querySelectorAll('*')).filter(e=>!['SCRIPT','STYLE','TEMPLATE'].includes(e.tagName)).map(e=>{const styles={};for(const pseudo of [null,'::before','::after']){const c=getComputedStyle(e,pseudo);if(pseudo&&['none','normal'].includes(c.content)){styles[pseudo]={content:c.content};continue;}styles[pseudo||'element']=props.map(k=>[k,c.getPropertyValue(k)]);}const r=e.getBoundingClientRect();return{tag:e.tagName,id:e.id,styles,rect:[r.x,r.y,r.width,r.height],text:e.childElementCount?undefined:e.textContent};});return{hash:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(data)))),x=>x.toString(16).padStart(2,'0')).join(''),elements:data.length};},stats[0].cssProps);}
async function settle(p){await p.mouse.move(0,0);await p.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 for(const[name,type]of Object.entries({chromium,firefox,webkit})){
  const browser=await type.launch(name==='chromium'?{executablePath:process.env.AUDIT_CHROME,args:['--no-sandbox','--js-flags=--expose-gc']}:{}),pages=[],contexts=[],errors=[],checks=[],layouts=[];
  try{
   for(const variant of ['baseline','candidate']){const c=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce',acceptDownloads:true,hasTouch:true});contexts.push(c);await configure(c);const p=await c.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/'+variant);await p.waitForFunction(()=>globalThis.__audit&&globalThis.__auditRng);}
   const parsed=await Promise.all(pages.map(p=>p.evaluate(c=>c.map(x=>{try{return __audit.parse(x);}catch(e){return{name:e.name,message:e.message,cause:e.cause?.name};}}),corpus)));assert.deepEqual(parsed[0],parsed[1]);assert.equal(parsed[0][3].addr.sigungu,'중구');assert.equal(parsed[0][4].addr.sigungu,'수원시 팔달구');assert.equal(parsed[0][15].name,'Error');for(let i=0;i<corpus.length;i++)checks.push('parser-case-'+i);
   const rng=await Promise.all(pages.map(p=>p.evaluate(values=>values.map(n=>__audit.generate(n)),numbers)));assert.deepEqual(rng[0],rng[1]);for(const t of rng[0]){assert.equal(t.split('\n').length,17);assert.match(t,/NMS 포탈 주소: .*\(.+\)/);}checks.push('132-deterministic-rng-outputs');
   for(let v=0;v<2;v++){
    const result=await pages[v].evaluate(async()=>{
     const name='dead-audit-'+crypto.randomUUID(),storeName='cache';const db=await new Promise((resolve,reject)=>{const q=indexedDB.open(name,1);q.onupgradeneeded=()=>q.result.createObjectStore(storeName,{keyPath:'key'}).createIndex('savedAt','savedAt');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});
     const txRun=op=>new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readwrite');tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error);op(tx.objectStore(storeName));});
     const all=()=>new Promise((resolve,reject)=>{const q=db.transaction(storeName).objectStore(storeName).getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});
     const out=[];try{for(const count of [0,3,10035]){const now=Date.now();await txRun(s=>{s.clear();for(let i=0;i<count;i++)s.put({key:'valid-'+String(i).padStart(5,'0'),savedAt:now-100000+i});for(let i=0;i<3;i++)s.put({key:'expired-'+i,savedAt:now-__audit.CONFIG.REVERSE_CACHE_TTL_MS-100000});});let calls=[];await txRun(s=>__audit.maintain(s,n=>calls.push(n)));const rows=await all();if(calls.length!==1||calls[0]!==Math.min(count,10000)||rows.length!==calls[0]||rows.some(r=>r.key.startsWith('expired-')))throw Error('maintenance contract');if(count>10000&&rows[0].key!=='valid-00035')throw Error('prune order');out.push({input:count,rows:rows.length,callbacks:calls.length,first:rows[0]?.key,last:rows.at(-1)?.key});}
      let called=0;await new Promise(resolve=>{const tx=db.transaction(storeName,'readwrite');tx.onabort=resolve;tx.onerror=()=>{};__audit.maintain(tx.objectStore(storeName),()=>called++);tx.abort();});if(called)throw Error('aborted callback');out.push({abortedCallback:called});
     }finally{db.close();await new Promise((resolve,reject)=>{const q=indexedDB.deleteDatabase(name);q.onsuccess=resolve;q.onerror=()=>reject(q.error);q.onblocked=()=>reject(Error('cleanup blocked'));});}return out;
    });assert.deepEqual(result,[{input:0,rows:0,callbacks:1,first:undefined,last:undefined},{input:3,rows:3,callbacks:1,first:'valid-00000',last:'valid-00002'},{input:10035,rows:10000,callbacks:1,first:'valid-00035',last:'valid-10034'},{abortedCallback:0}]);checks.push(['baseline','candidate'][v]+'-cache-expiry-prune-abort-cleanup');
   }
   const scenarios=[];for(const width of [320,375,700,768,1100,1101,1535,1680])for(const theme of ['light','dark'])scenarios.push({width,theme,n:4,status:'idle',pending:false,media:'screen'});for(const status of ['running','paused','pausing','stopping','parsing','idle'])scenarios.push({width:375,theme:'light',n:status==='running'?4:0,status,pending:status==='running',media:'screen'});for(const width of [375,1440])scenarios.push({width,theme:'light',n:4,status:'idle',pending:false,media:'print'});
   for(let n=0;n<scenarios.length;n++){const s=scenarios[n],snap=[],png=[];for(let v=0;v<2;v++){const p=pages[v];await p.setViewportSize({width:s.width,height:1050});await p.emulateMedia({media:s.media,reducedMotion:'reduce'});await p.evaluate(s=>{document.documentElement.dataset.theme=s.theme;__audit.seed(s.n,10,0,s.status,s.pending);},s);await settle(p);snap.push(await digestState(p));png.push(await p.screenshot({fullPage:true,animations:'disabled'}));if(s.pending){assert.equal(await p.locator('.loading-rows').evaluate(e=>getComputedStyle(e).display),'table-footer-group');assert.equal(await p.locator('#prog').getAttribute('aria-labelledby'),'prog-label');checks.push(['baseline','candidate'][v]+'-live-loading-and-progress-label');}}
    assert.deepEqual(snap[0],snap[1],'all author styles/geometry '+JSON.stringify(s));layouts.push({scenario:s,computedSHA256:snap[0].hash,pixelExact:png[0].equals(png[1]),pngSHA256:png.map(sha)});checks.push('complete-styles-geometry-'+n);if([0,16,22].includes(n)||!png[0].equals(png[1]))for(let v=0;v<2;v++)fs.writeFileSync(path.join(evidence,name+'-layout-'+n+'-'+v+'.png'),png[v]);if(n%8===0)console.log(name+' layout '+(n+1)+'/'+scenarios.length);
   }
   const aria=[];for(const p of pages){await p.emulateMedia({media:'screen'});await p.evaluate(()=>__audit.seed());aria.push(await p.locator('body').ariaSnapshot());}assert.equal(aria[0],aria[1]);checks.push('full-page-accessibility');
   const liveOutputs=[];for(let v=0;v<2;v++){const p=pages[v];await p.setViewportSize({width:1440,height:1050});await p.locator('#file').setInputFiles({name:'fixture.txt',mimeType:'text/plain',buffer:Buffer.from('대한민국 위경도: 37.5665, 126.9780\n세계 위경도: -90, -180\n대한민국 위경도: 37.5665, 126.9780\n세계 위경도: 91, 0\n')});await p.locator('#parse').click();await p.waitForFunction(()=>document.querySelector('#coords-count').textContent==='3'&&!document.querySelector('#start').disabled);await p.locator('#start').click();await p.waitForFunction(()=>document.querySelector('#cnt-success').textContent==='3'&&!document.querySelector('#start').disabled);assert.equal(await p.locator('#tbl tbody tr').count(),3);await p.locator('#filter-q').fill('서울');await p.waitForFunction(()=>document.querySelector('#tbl tbody').children.length===2);await p.locator('#filter-clear span').click();await p.waitForFunction(()=>document.querySelector('#tbl tbody').children.length===3);assert.equal(await p.locator('#filter-q').inputValue(),'');await p.locator('#tbl tbody .map-btn').first().click();assert.equal(await p.locator('#map-popover').evaluate(e=>e.matches(':popover-open')),true);await p.keyboard.press('Escape');const download=p.waitForEvent('download');await p.locator('#export').click();const csv=fs.readFileSync(await(await download).path(),'utf8');assert.match(csv,/OpenStreetMap contributors/);
    await p.locator('#num64').fill('0x0112233445566778');await p.locator('#suppValues').fill('invalid-unused');await p.locator('#runBtn').click();await p.waitForFunction(()=>document.querySelector('#meta').textContent.includes('완료'));const text=await p.locator('#output .coords-content').textContent();assert.equal(text.trim().split('\n').length,17);const saved=p.waitForEvent('download');await p.locator('#saveOutput').click();const file=fs.readFileSync(await(await saved).path(),'utf8');assert.equal(file.replace(/^\uFEFF/,'').trim(),text.trim());liveOutputs.push({csv,text,file});await p.locator('#clearBtn').click();assert.equal(await p.locator('#output .coords-content').textContent(),'');checks.push(['baseline','candidate'][v]+'-HTTP-file-coords-filter-map-CSV-RNG-save-clear');}
   assert.deepEqual(liveOutputs[0],liveOutputs[1]);checks.push('exact-CSV-manual-output-download');
   for(let v=0;v<2;v++){const p=pages[v];await p.evaluate(()=>__audit.seed(5000));const nav=p.locator('#page-numbers');const current=()=>nav.locator('[aria-current="page"]');const button=n=>nav.locator('button[data-page="'+(n-1)+'"]');for(const key of ['Enter','Space']){await button(2).press(key);assert.equal(await current().textContent(),'2');await button(1).click();checks.push(['baseline','candidate'][v]+'-native-page-'+key);}await p.setViewportSize({width:375,height:1050});await button(2).tap();assert.equal(await current().textContent(),'2');await button(1).click();await p.setViewportSize({width:1440,height:1050});checks.push(['baseline','candidate'][v]+'-native-page-touch');
    for(const bad of ['-1','500','1.5','NaN']){await button(2).evaluate((e,n)=>{const old=e.dataset.page;e.dataset.page=n;e.click();e.dataset.page=old;},bad);assert.equal(await current().textContent(),'1');checks.push(['baseline','candidate'][v]+'-page-bound-'+bad);}
    await button(2).evaluate(e=>{e.disabled=true;e.click();e.disabled=false;});assert.equal(await current().textContent(),'1');await button(2).evaluate(e=>{const s=document.createElement('span');s.textContent=e.textContent;e.replaceChildren(s);});await button(2).locator('span').click();assert.equal(await current().textContent(),'2');assert.ok(await nav.locator(':scope > *').count()<=7);checks.push(['baseline','candidate'][v]+'-disabled-nested-bounded-nav');
    for(const key of ['Enter','Space','touch']){await p.locator('#filter-q').fill('not-present');await p.waitForFunction(()=>document.querySelector('#result-pages').hidden);if(key==='touch')await p.locator('#filter-clear').tap();else await p.locator('#filter-clear').press(key);await p.waitForFunction(()=>document.querySelectorAll('#tbl tbody tr').length===10);assert.equal(await p.locator('#filter-q').inputValue(),'');assert.equal(await current().textContent(),'1');checks.push(['baseline','candidate'][v]+'-filter-clear-'+key);}
   }
   for(const variant of ['baseline','candidate']){const p=await contexts[variant==='baseline'?0:1].newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/closed-'+variant);assert.equal(await p.locator('.manual-rng').evaluate(e=>e.open),false);assert.equal(await p.evaluate(()=>typeof globalThis.__auditRng),'undefined');await p.locator('.manual-rng > summary').click();await p.waitForFunction(()=>globalThis.__auditRng);await p.locator('#num64').fill('0x0112233445566778');await p.locator('#runBtn').click();await p.waitForFunction(()=>document.querySelector('#meta').textContent.includes('완료'));checks.push(variant+'-initially-closed-lazy-RNG');await p.close();}
   for(const p of pages){await p.evaluate(()=>__audit.seed(4,10,0,'running',true));await p.emulateMedia({reducedMotion:'no-preference'});assert.equal(await p.locator('.skeleton-bar').first().evaluate(e=>getComputedStyle(e).animationName),'skeleton');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.skeleton-bar').first().evaluate(e=>getComputedStyle(e).animationName),'none');}checks.push('skeleton-live-normal-and-reduced-motion');
   const samples={};for(const workload of output.contract.changedWorkloads){const series=[[],[]];if(['page-10','page-100','nav-5000','current-page','filter-clear-scheduling'].includes(workload)){const n=workload==='nav-5000'?5000:200,size=workload==='page-100'?100:10;for(const p of pages)await p.evaluate(([n,size])=>__audit.seed(n,size),[n,size]);}
    for(let pair=-10;pair<40;pair++)for(const v of pair%2===0?[0,1]:[1,0]){
     const ms=await pages[v].evaluate(({workload,corpus,numbers})=>{let sink=0;const start=performance.now();if(workload==='parser'){for(let j=0;j<200;j++)for(const c of corpus){try{sink+=__audit.parse(c).addr.sido.length;}catch(e){sink+=e.message.length;}}}else if(workload==='rng-single'){for(let j=0;j<100;j++)sink+=__audit.generate('77162851027281784').length;}else if(workload==='rng-bulk'){for(const n of numbers.slice(-128))sink+=__audit.generate(n).length;}else if(workload==='ui-state'){for(let j=0;j<1000;j++){__audit.state(['idle','running','paused','pausing','stopping','parsing'][j%6]);sink+=document.querySelector('#start').disabled?1:0;}}else if(workload==='filter-clear-scheduling'){const button=document.querySelector('#filter-clear');for(let j=0;j<1000;j++){document.querySelector('#filter-q').value='not-present';button.click();if(document.querySelector('#filter-q').value!=='')throw Error('query retained');sink++;}}else{for(let j=0;j<20;j++){const target=workload==='current-page'?__audit.page():1-__audit.page();document.querySelector('#page-numbers button[data-page="'+target+'"]').click();if(__audit.page()!==target)throw Error('page not applied');sink+=document.querySelector('#tbl').getBoundingClientRect().height;}}if(!sink)throw Error('benchmark no output');const reps=workload==='parser'?200*corpus.length:workload==='rng-single'?100:workload==='rng-bulk'?128:workload==='ui-state'||workload==='filter-clear-scheduling'?1000:20;return(performance.now()-start)/reps;},{workload,corpus,numbers});if(pair>=0)series[v].push(ms);
    }samples[workload]=series;console.log(name+' measured '+workload);
   }
   for(const p of pages)await p.evaluate(()=>__audit.state('idle'));assert.deepEqual(errors,[]);checks.push('no-pageerrors');output.browsers[name]={complete:true,version:browser.version(),checks,samples,layouts};fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify(output,null,2));console.log(name+' complete '+checks.length+' checks');
  }finally{await browser.close();}
 }
 console.log('AUDIT_SOURCE '+JSON.stringify(stats.map(({selectors,cssProps,...rest})=>rest)));
 console.log('AUDIT_RESULTS '+JSON.stringify(output));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
